# Generated by Django 5.0.2 on 2024-02-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_pdfstorage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='drive.pdfstorage')),
            ],
        ),
    ]
