# Generated by Django 5.0.1 on 2024-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_pdfstorage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pdfstorage',
            name='images',
            field=models.ManyToManyField(blank=True, to='drive.imagestorage'),
        ),
    ]
