# Generated by Django 5.0.1 on 2024-02-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_imagestorage_pdfstorage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfstorage',
            name='images',
        ),
        migrations.AddField(
            model_name='imagestorage',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='drive.pdfstorage'),
        ),
    ]
