# Generated by Django 5.0.2 on 2024-02-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_pdfpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfpage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='pdf_images'),
        ),
    ]
