# Generated by Django 5.0.2 on 2024-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_pdfpage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFPage',
        ),
    ]
