# Generated by Django 5.0.2 on 2024-02-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_delete_pdfpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='pdf_images')),
                ('page_number', models.PositiveBigIntegerField()),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.pdfstorage')),
            ],
        ),
    ]
